FROM nginx
COPY . /usr/share/nginx/html

LABEL maintainer="R3d5tar" \
      repo="https://github.com/R3d5tar/EDHScoreboard"

CMD /bin/bash -c "envsubst < /usr/share/nginx/html/env.js.template > /usr/share/nginx/html/env.js && exec nginx -g 'daemon off;'"